### ISSUE TITLE
User Story: Create Read Functionality on Pilots and Mechs

### ISSUE THREAD

**Issue by bovinehero** [bovinehero/battletech-inventory#11]
## Context

As a battletech player
I need a way to fetch information about pilots and mechs
so that I can see which units are available for the campaign

## Acceptence Criteria

- Create List View of Pilots and Mechs
- Create Detail View of Pilots and their Mech

## Tasks

- [x] Build Index landing Page for navigation
- [x] Build List View for all pilots and their mechs
- [x] Build a detailed View for any given pilot and their mech

**Comment by bovinehero** [comment]
Base dB models tweaked to allow for a stock of pilots and mechs, as well as an Active pairing of pilot to mech.

Working [branch](https://github.com/bovinehero/battletech-inventory/tree/read-all-the-things)  for in Progress work

**Comment by bovinehero** [comment]
Read views complete
