### ISSUE TITLE
User Story: Implement Create/Delete new Pilot and Mech functionality

### ISSUE THREAD

**Issue by bovinehero** [bovinehero/battletech-inventory#13]
## Context

As a battletech GM
I need a way to create/delete pilots and mechs
so that as the campaign progresses I can recruit new pilots and mechs

## Acceptence Criteria

- Enable users to create/delete information about Pilots and Mechs

## Tasks

- [x] Create delete mech view and functionality
- [x] Create create mech view and functionality
- [x] Create delete pilot view and functionality
- [x] Create delete pilot view and functionality

**Comment by bovinehero** [comment]
basic Poc has  full CRUD functionality
