### ISSUE TITLE
User Story: Setup frontend

### ISSUE THREAD

**Issue by bovinehero** [bovinehero/battletech-inventory#14]
## Context

As a battletech player
I need a way to easily navigate around the site
so that I can interact with pilot and mech details

## Acceptence Criteria

- Set up responsive front end that allows CRUD functionality

## Tasks

- [x] Create responsive enhanced bootstrap theme
- [x] Create Navbar for views & Forms
- [x] Implement remote static resources
- [x] Deploy to heroku for testing

**Comment by bovinehero** [comment]
Issues with static files, forced a pivot to new repo to go back to basics
