### ISSUE TITLE
User Story: Django Base Setup

### ISSUE THREAD

**Issue by bovinehero** [bovinehero/battletech-inventory#5]
## Context

As a developer
I need my base django dev env configured
so that I can begin devlopement

## Acceptence Criteria

- Standard Django app should be workable from local dev
- Code should be in git repo
- Custom settings should be specified to enable remote dev as well

## Tasks

- [X] Set up local dev env
- [x] Put in hello world index view placeholder
- [x] Integrate with heroku, remote db and CMS

**Comment by bovinehero** [comment]
Use django-starter [repo](https://github.com/bovinehero/django-starter) to quickstart a bootstrap enabled django app.

Will require a basic dB model to complete integration task

**Comment by bovinehero** [comment]
Task blocked until other epic stories are completed.
