### ISSUE TITLE
User Story: Admin app setup

### ISSUE THREAD

**Issue by bovinehero** [bovinehero/battletech-inventory#8]
## Context

As a site admin
I need a basic admin panel setup
so that perform admin functions and see visible results of models

## Acceptence Criteria
- Create a first draft set of models and push them to the admin view

## Tasks
- [x] Design RDBMS for managing Pilot to Mech relationships
- [x] Create base Pilots Model
- [x] Create base Mechs Model
- [x] Push to admin view

**Comment by bovinehero** [comment]
Base model for pilot and created, design diagram is pending.

**Comment by bovinehero** [comment]
diagram and testcases created
